Fix Requires version format
Avoid the rpmbuild error
error: line 18: Dependency tokens must begin with alpha-numeric, '_' or
'/': Requires: ruby19 [">= 1.9.2"]

For some reason  spec.required_ruby_version is array-like and requires
iterating to get this:
Requires: ruby19 >= 1.9.2
instead of this
Requires: ruby19 [">= 1.9.2"]

The same technique is used by the fedora templates in gem2rpm.